# Render Blueprint for Service Request Management System
# This file defines the infrastructure for deploying on Render.com

services:
  # PostgreSQL Database (Render's free tier uses PostgreSQL instead of MySQL)
  - type: pserv
    name: service-request-db
    env: docker
    plan: free
    region: oregon
    
  # Backend API Service
  - type: web
    name: service-request-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install && npm run migrate
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: DATABASE_URL
        fromDatabase:
          name: service-request-db
          property: connectionString
    healthCheckPath: /api/health
    
  # Frontend Static Site
  - type: web
    name: service-request-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: service-request-backend
          envVarKey: RENDER_EXTERNAL_URL
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: service-request-db
    databaseName: service_requests_db
    user: admin
    plan: free
    region: oregon
